### ISSUE TITLE
 What are the possible reasons of the errors "Cannot commit index" and "Cannot apply non-sequential index" ? 

### ISSUE THREAD

**Issue by StackWu** [atomix/atomix#282]
Pardon my ignorance showing but, I'm confused about the Atomix. What are the possible reasons of the errors "Cannot commit index" and "non-sequential index" ? 

Hi, my friends ! I develop my system based on your great distributed coordination framework. But I have some problems. Could you give me some advice ? please.

The error “**ERROR i.a.p.raft.impl.RaftServiceManager - RaftServer- Cannot commit index 5087530**” occurs sometimes when I send lots of requests to the cluster in a short time. For instance, I set the concurrent connections to 256 and send request repeatedly.

Similarly, The error “**Cannot apply non-sequential index 1264553 unless it’s the first entry in the log 1**” occurs “randomly” . And then the client can’t send request anymore. 

Can Atomix fix these errors by itself ? What should I do to prevent such mistakes ? Thank you !

**Comment by kuujo** [comment]
These errors were notifications of bugs and should be fixed in the latest release (2.0.2) and in master. Are you using Atomix 2.0.2? We'll be cutting a 2.0.3 release this weekend as well.

Both of these errors were the result of a race condition inside the `RaftServiceManager`. When entries were being read by the manager and applied to state machines, reads were being done in a separate thread. But some fields inside the shared log were not volatile, so the log iterator was skipping some entries at certain points in the log (on segment roll overs), leading to inconsistencies when applying the entries. Guards against applying entries out of order or skipping entries (thus resulting in incorrect state) were correct in throwing these errors in those cases.

The 2.0.2 release fixes the thread safety issue in the `RaftServiceManager` and also fixes some bugs in the snapshot replication protocol as well. Atomix 2.0.2 passed QA but has some performance issues relating to log compaction. So, Atomix 2.0.3 improves log compaction efficiency by avoiding compaction when the server or individual services are under high load.

Please verify that this is still an issue in Atomix 2.0.2 or master and update this issue. We have not been able to reproduce it in 2.0.2.

**Comment by StackWu** [comment]
@kuujo 
Thanks for your detailed reply .

I'm using Atomix 2.0.2 release which is the latest version. The problem that "cannot commit index" still occured under high load. But another problem "non-sequential index" has disappeared. I think I need to check my code and try it again next week. I can't wait to see your new great and exciting version.

Thanks again for your work.
